name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Flet
      run: pip install flet

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Build APK
      run: |
        flutter create .
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
