name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          python3-pip \
          libffi-dev \
          libssl-dev \
          libncurses5 \
          libsqlite3-dev \
          libgdbm-dev \
          libnss3-dev \
          zlib1g-dev \
          libbz2-dev \
          libreadline-dev \
          liblzma-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libfreetype6-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff5-dev \
          libx11-dev \
          libsmpeg-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          python3-setuptools \
          libffi-dev \
          libssl-dev \
          adb \
          clang \
          cmake \
          pkg-config \
          libtool \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          xclip \
          libmtdev-dev \
          libglfw3 \
          libglfw3-dev \
          libudev-dev

        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-apk
        path: bin/*.apk
